server:
  port: 8081
spring:
  profiles:
    active: user
  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/db
    username: root
    password: root
  config:
    import: optional:configserver:lb://CONFIG-SERVICE/USER-SERVICE/user/default
  jpa:
    hibernate:
      ddl-auto: update
 
springdoc:
  api-docs:
      path: /v3/api-docs
  swagger-ui:
      path: /swagger-ui.html
  